
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tirwrfjxvhlkmcgmnzca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcndyZmp4dmhsa21jZ21uemNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjQzMzQsImV4cCI6MjA2NDQ0MDMzNH0.BfzV8TfUKrb25TA9B_HmG9BcvHa0ApLU_pArYjZ8QZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize admin user function
export const initializeAdmin = async (): Promise<{ success: boolean; message?: string; error?: string }> => {
  try {
    console.log('Verificando se admin já existe...');
    
    // Check if admin user already exists
    const { data: existingUser } = await supabase
      .from('profiles')
      .select('id, email, role')
      .eq('email', 'renan@innfokus.com.br')
      .single();

    if (existingUser) {
      console.log('Admin já existe:', existingUser);
      return { 
        success: true, 
        message: 'Admin user already exists' 
      };
    }

    console.log('Admin não encontrado, executando função de criação...');
    
    // Call the database function to create admin user
    const { error } = await supabase.rpc('create_admin_user');
    
    if (error) {
      console.error('Erro ao criar admin:', error);
      return { 
        success: false, 
        error: error.message 
      };
    }

    console.log('Admin criado com sucesso!');
    return { 
      success: true, 
      message: 'Admin user created successfully' 
    };
  } catch (error: any) {
    console.error('Erro inesperado ao inicializar admin:', error);
    return { 
      success: false, 
      error: error.message || 'Unexpected error occurred' 
    };
  }
};
