
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufvuiddrtbzdpjpnmzgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdnVpZGRydGJ6ZHBqcG5temd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDA0NjEsImV4cCI6MjA2NDM3NjQ2MX0.a1E8iwQve37VtGPEpmv0AYbLqTSpq_-yIct-QxTelzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize admin user
export const initializeAdmin = async () => {
  try {
    console.log('Inicializando usuário admin...');
    
    // Check if admin already exists
    const { data: existingProfile } = await supabase
      .from('profiles')
      .select('*')
      .eq('email', 'renan@innfokus.com.br')
      .single();

    if (existingProfile) {
      console.log('Admin já existe:', existingProfile);
      return { success: true, message: 'Admin já existe' };
    }

    // Create admin user via auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: 'renan@innfokus.com.br',
      password: 'pass@admin',
      options: {
        data: {
          name: 'Administrador',
          role: 'admin'
        }
      }
    });

    if (authError) {
      console.error('Erro ao criar admin:', authError);
      return { success: false, error: authError.message };
    }

    console.log('Admin criado com sucesso:', authData);
    return { success: true, message: 'Admin criado com sucesso' };
  } catch (error) {
    console.error('Erro inesperado ao inicializar admin:', error);
    return { success: false, error: 'Erro inesperado' };
  }
};
